"""Boundary lifecycle states for the adaptive review workflow."""

from __future__ import annotations

from enum import Enum


class BoundaryState(Enum):
    """The lifecycle state of a track boundary.

    AUTO
        Created by the detector. May be moved by future reanalysis.

    LOCKED
        Manually positioned by the user. The detector must never move this.

    VERIFIED
        Explicitly accepted by the user. Treated as final.

    SUGGESTED
        Candidate improvement generated by local reanalysis. Not yet applied.
    """

    AUTO = "auto"
    LOCKED = "locked"
    VERIFIED = "verified"
    SUGGESTED = "suggested"

    def display_label(self, confidence: float | None = None) -> str:
        """Return a human-readable label for the review table Status column."""

        if self is BoundaryState.LOCKED:
            return "LOCKED"

        if self is BoundaryState.VERIFIED:
            return "VERIFIED"

        if self is BoundaryState.SUGGESTED:
            return "SUGGESTED"

        # AUTO: show confidence if available
        if confidence is not None:
            return f"AUTO ({confidence * 100:.0f}%)"

        return "AUTO"

    def is_user_controlled(self) -> bool:
        """Return True when no automated process may move this boundary."""
        return self in {BoundaryState.LOCKED, BoundaryState.VERIFIED}
