from dataclasses import dataclass
from pathlib import Path
import subprocess


@dataclass
class Fingerprint:
    """An acoustic fingerprint generated by Chromaprint."""

    duration: int
    fingerprint: str


class Fingerprinter:
    """Generate acoustic fingerprints using fpcalc."""

    def fingerprint(self, filename: str) -> Fingerprint:
        path = Path(filename)

        if not path.exists():
            raise FileNotFoundError(path)

        try:
            result = subprocess.run(
                ["fpcalc", str(path)],
                capture_output=True,
                text=True,
                check=True,
            )
        except FileNotFoundError:
            raise RuntimeError("fpcalc was not found. Please install Chromaprint.")

        duration = 0
        fingerprint = ""

        for line in result.stdout.splitlines():
            if line.startswith("DURATION="):
                duration = int(line.split("=", 1)[1])

            elif line.startswith("FINGERPRINT="):
                fingerprint = line.split("=", 1)[1]

        if not fingerprint:
            raise RuntimeError("Failed to generate fingerprint.")

        return Fingerprint(
            duration=duration,
            fingerprint=fingerprint,
        )
